// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/earth/base/order/order.proto

// Protobuf Java Version: 3.25.3
package com.earth.base.order;

public interface NewOrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.earth.base.order.NewOrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 订单ID
   * </pre>
   *
   * <code>int64 order_id = 1;</code>
   * @return The orderId.
   */
  long getOrderId();

  /**
   * <code>int64 code = 2;</code>
   * @return The code.
   */
  long getCode();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string crossAvailable = 4;</code>
   * @return The crossAvailable.
   */
  java.lang.String getCrossAvailable();
  /**
   * <code>string crossAvailable = 4;</code>
   * @return The bytes for crossAvailable.
   */
  com.google.protobuf.ByteString
      getCrossAvailableBytes();

  /**
   * <pre>
   * 订单状态，必须字段
   * </pre>
   *
   * <code>.com.earth.base.order.OrderStatusEnum status = 5;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <pre>
   * 订单状态，必须字段
   * </pre>
   *
   * <code>.com.earth.base.order.OrderStatusEnum status = 5;</code>
   * @return The status.
   */
  com.earth.base.order.OrderStatusEnum getStatus();
}
