// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/earth/base/order/order.proto

// Protobuf Java Version: 3.25.3
package com.earth.base.order;

public final class OrderServiceProto {
  private OrderServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_earth_base_order_NewOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_earth_base_order_NewOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_earth_base_order_NewOrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_earth_base_order_NewOrderResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n com/earth/base/order/order.proto\022\024com." +
      "earth.base.order\032(com/earth/base/common/" +
      "order_common.proto\"\347\013\n\017NewOrderRequest\022\022" +
      "\n\naccount_id\030\001 \001(\003\022\027\n\017client_order_id\030\002 " +
      "\001(\t\022\021\n\tsymbol_id\030\003 \001(\t\0228\n\norder_type\030\004 \001" +
      "(\0162$.com.earth.base.common.OrderTypeEnum" +
      "\022B\n\rtime_in_force\030\005 \001(\0162+.com.earth.base" +
      ".common.OrderTimeInForceEnum\0222\n\004side\030\006 \001" +
      "(\0162$.com.earth.base.common.OrderSideEnum" +
      "\022-\n\005price\030\007 \001(\0132\036.com.earth.base.common." +
      "Decimal\0220\n\010quantity\030\010 \001(\0132\036.com.earth.ba" +
      "se.common.Decimal\022.\n\006amount\030\t \001(\0132\036.com." +
      "earth.base.common.Decimal\022\023\n\013exchange_id" +
      "\030\n \001(\003\0226\n\016maker_fee_rate\030\013 \001(\0132\036.com.ear" +
      "th.base.common.Decimal\0226\n\016taker_fee_rate" +
      "\030\014 \001(\0132\036.com.earth.base.common.Decimal\0220" +
      "\n\010leverage\030\r \001(\0132\036.com.earth.base.common" +
      ".Decimal\022\020\n\010is_close\030\016 \001(\010\022\034\n\024is_liquida" +
      "tion_order\030\017 \001(\010\022\016\n\006org_id\030\020 \001(\003\022\021\n\tsign" +
      "_time\030\021 \001(\003\022\022\n\nsign_nonce\030\022 \001(\t\022\023\n\013sign_" +
      "broker\030\023 \001(\t\0225\n\rtrigger_price\030\024 \001(\0132\036.co" +
      "m.earth.base.common.Decimal\0226\n\016original_" +
      "price\030\025 \001(\0132\036.com.earth.base.common.Deci" +
      "mal\022G\n\nextra_flag\030\026 \001(\01623.com.earth.base" +
      ".order.NewOrderRequest.ExtraFlagEnum\0228\n\020" +
      "maker_bonus_rate\030\027 \001(\0132\036.com.earth.base." +
      "common.Decimal\022\024\n\014order_source\030\030 \001(\003\0228\n\014" +
      "base_request\030d \001(\0132\".com.earth.base.comm" +
      "on.BaseRequest\022\021\n\tdeduction\030\032 \001(\t\022\"\n\032int" +
      "egral_num_expect_frozen\030\033 \001(\003\022A\n\031integra" +
      "l_num_to_usdt_rate\030\034 \001(\0132\036.com.earth.bas" +
      "e.common.Decimal\022\031\n\021integral_num_used\030\035 " +
      "\001(\003\022\035\n\025integral_num_unfrozen\030\036 \001(\003\022\033\n\023in" +
      "tegral_num_remain\030\037 \001(\003\022\017\n\007isCross\030\031 \001(\010" +
      "\"\371\001\n\rExtraFlagEnum\022\013\n\007DEFAULT\020\000\022\036\n\032FOR_E" +
      "XTERNAL_MATCHED_ORDER\020\001\022\023\n\017LIQUI_IOC_ORD" +
      "ER\020\002\022\023\n\017LIQUI_ADL_ORDER\020\003\022\027\n\023FOR_MATCHED" +
      "_SUBSIDY\020\004\022\t\n\005INPUT\020h\022\014\n\010OPPONENT\020i\022\t\n\005Q" +
      "UEUE\020j\022\010\n\004OVER\020k\022\020\n\014MARKET_PRICE\020l\022\021\n\rHE" +
      "DGE_BINANCE\020\016\022\022\n\016ORDINARY_AGENT\020\017\022\021\n\rSPE" +
      "CIAL_AGENT\020\020\"\222\001\n\020NewOrderResponse\022\020\n\010ord" +
      "er_id\030\001 \001(\003\022\014\n\004code\030\002 \001(\003\022\017\n\007message\030\003 \001" +
      "(\t\022\026\n\016crossAvailable\030\004 \001(\t\0225\n\006status\030\005 \001" +
      "(\0162%.com.earth.base.order.OrderStatusEnu" +
      "m*\242\002\n\017OrderStatusEnum\022\007\n\003NEW\020\000\022\024\n\020PARTIA" +
      "LLY_FILLED\020\001\022\n\n\006FILLED\020\002\022\020\n\014DONE_FOR_DAY" +
      "\020\003\022\014\n\010CANCELED\020\004\022\014\n\010REPLACED\020\005\022\022\n\016PENDIN" +
      "G_CANCEL\020\006\022\014\n\010REJECTED\020\010\022\r\n\tSUSPENDED\020\t\022" +
      "\017\n\013PENDING_NEW\020\n\022\016\n\nCALCULATED\020\013\022\013\n\007EXPI" +
      "RED\020\014\022\030\n\024ACCEPTED_FOR_BIDDING\020\r\022\023\n\017PENDI" +
      "NG_REPLACE\020\016\022\022\n\016ADMIN_REJECTED\020\017\022\024\n\020EXPI" +
      "RED_CANCELED\020\0202l\n\014OrderService\022\\\n\013Create" +
      "Order\022%.com.earth.base.order.NewOrderReq" +
      "uest\032&.com.earth.base.order.NewOrderResp" +
      "onseB+\n\024com.earth.base.orderB\021OrderServi" +
      "ceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.earth.base.common.OrderCommonProto.getDescriptor(),
        });
    internal_static_com_earth_base_order_NewOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_earth_base_order_NewOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_earth_base_order_NewOrderRequest_descriptor,
        new java.lang.String[] { "AccountId", "ClientOrderId", "SymbolId", "OrderType", "TimeInForce", "Side", "Price", "Quantity", "Amount", "ExchangeId", "MakerFeeRate", "TakerFeeRate", "Leverage", "IsClose", "IsLiquidationOrder", "OrgId", "SignTime", "SignNonce", "SignBroker", "TriggerPrice", "OriginalPrice", "ExtraFlag", "MakerBonusRate", "OrderSource", "BaseRequest", "Deduction", "IntegralNumExpectFrozen", "IntegralNumToUsdtRate", "IntegralNumUsed", "IntegralNumUnfrozen", "IntegralNumRemain", "IsCross", });
    internal_static_com_earth_base_order_NewOrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_earth_base_order_NewOrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_earth_base_order_NewOrderResponse_descriptor,
        new java.lang.String[] { "OrderId", "Code", "Message", "CrossAvailable", "Status", });
    com.earth.base.common.OrderCommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
