// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/earth/base/common/order_common.proto

// Protobuf Java Version: 3.25.3
package com.earth.base.common;

public interface BaseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.earth.base.common.BaseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * alias broker_id or org_id
   * </pre>
   *
   * <code>int64 organization_id = 1;</code>
   * @return The organizationId.
   */
  long getOrganizationId();

  /**
   * <code>int64 request_time = 2;</code>
   * @return The requestTime.
   */
  long getRequestTime();

  /**
   * <pre>
   *用户，券商，券商代表用户
   * </pre>
   *
   * <code>.com.earth.base.common.BaseRequest.InvokerTypeEnum invoke_type = 3;</code>
   * @return The enum numeric value on the wire for invokeType.
   */
  int getInvokeTypeValue();
  /**
   * <pre>
   *用户，券商，券商代表用户
   * </pre>
   *
   * <code>.com.earth.base.common.BaseRequest.InvokerTypeEnum invoke_type = 3;</code>
   * @return The invokeType.
   */
  com.earth.base.common.BaseRequest.InvokerTypeEnum getInvokeType();

  /**
   * <code>int64 broker_user_id = 4;</code>
   * @return The brokerUserId.
   */
  long getBrokerUserId();

  /**
   * <code>int64 account_id = 5;</code>
   * @return The accountId.
   */
  long getAccountId();
}
