// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/earth/base/common/order_common.proto

// Protobuf Java Version: 3.25.3
package com.earth.base.common;

/**
 * Protobuf type {@code com.earth.base.common.BaseRequest}
 */
public final class BaseRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.earth.base.common.BaseRequest)
    BaseRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BaseRequest.newBuilder() to construct.
  private BaseRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BaseRequest() {
    invokeType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BaseRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.earth.base.common.OrderCommonProto.internal_static_com_earth_base_common_BaseRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.earth.base.common.OrderCommonProto.internal_static_com_earth_base_common_BaseRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.earth.base.common.BaseRequest.class, com.earth.base.common.BaseRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code com.earth.base.common.BaseRequest.InvokerTypeEnum}
   */
  public enum InvokerTypeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>USER = 1;</code>
     */
    USER(1),
    /**
     * <code>ORGANIZATION = 2;</code>
     */
    ORGANIZATION(2),
    /**
     * <code>AGENT_OF_USER = 3;</code>
     */
    AGENT_OF_USER(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>USER = 1;</code>
     */
    public static final int USER_VALUE = 1;
    /**
     * <code>ORGANIZATION = 2;</code>
     */
    public static final int ORGANIZATION_VALUE = 2;
    /**
     * <code>AGENT_OF_USER = 3;</code>
     */
    public static final int AGENT_OF_USER_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static InvokerTypeEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static InvokerTypeEnum forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return USER;
        case 2: return ORGANIZATION;
        case 3: return AGENT_OF_USER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<InvokerTypeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        InvokerTypeEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<InvokerTypeEnum>() {
            public InvokerTypeEnum findValueByNumber(int number) {
              return InvokerTypeEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.earth.base.common.BaseRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final InvokerTypeEnum[] VALUES = values();

    public static InvokerTypeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private InvokerTypeEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.earth.base.common.BaseRequest.InvokerTypeEnum)
  }

  public static final int ORGANIZATION_ID_FIELD_NUMBER = 1;
  private long organizationId_ = 0L;
  /**
   * <pre>
   * alias broker_id or org_id
   * </pre>
   *
   * <code>int64 organization_id = 1;</code>
   * @return The organizationId.
   */
  @java.lang.Override
  public long getOrganizationId() {
    return organizationId_;
  }

  public static final int REQUEST_TIME_FIELD_NUMBER = 2;
  private long requestTime_ = 0L;
  /**
   * <code>int64 request_time = 2;</code>
   * @return The requestTime.
   */
  @java.lang.Override
  public long getRequestTime() {
    return requestTime_;
  }

  public static final int INVOKE_TYPE_FIELD_NUMBER = 3;
  private int invokeType_ = 0;
  /**
   * <pre>
   *用户，券商，券商代表用户
   * </pre>
   *
   * <code>.com.earth.base.common.BaseRequest.InvokerTypeEnum invoke_type = 3;</code>
   * @return The enum numeric value on the wire for invokeType.
   */
  @java.lang.Override public int getInvokeTypeValue() {
    return invokeType_;
  }
  /**
   * <pre>
   *用户，券商，券商代表用户
   * </pre>
   *
   * <code>.com.earth.base.common.BaseRequest.InvokerTypeEnum invoke_type = 3;</code>
   * @return The invokeType.
   */
  @java.lang.Override public com.earth.base.common.BaseRequest.InvokerTypeEnum getInvokeType() {
    com.earth.base.common.BaseRequest.InvokerTypeEnum result = com.earth.base.common.BaseRequest.InvokerTypeEnum.forNumber(invokeType_);
    return result == null ? com.earth.base.common.BaseRequest.InvokerTypeEnum.UNRECOGNIZED : result;
  }

  public static final int BROKER_USER_ID_FIELD_NUMBER = 4;
  private long brokerUserId_ = 0L;
  /**
   * <code>int64 broker_user_id = 4;</code>
   * @return The brokerUserId.
   */
  @java.lang.Override
  public long getBrokerUserId() {
    return brokerUserId_;
  }

  public static final int ACCOUNT_ID_FIELD_NUMBER = 5;
  private long accountId_ = 0L;
  /**
   * <code>int64 account_id = 5;</code>
   * @return The accountId.
   */
  @java.lang.Override
  public long getAccountId() {
    return accountId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (organizationId_ != 0L) {
      output.writeInt64(1, organizationId_);
    }
    if (requestTime_ != 0L) {
      output.writeInt64(2, requestTime_);
    }
    if (invokeType_ != com.earth.base.common.BaseRequest.InvokerTypeEnum.UNKNOWN.getNumber()) {
      output.writeEnum(3, invokeType_);
    }
    if (brokerUserId_ != 0L) {
      output.writeInt64(4, brokerUserId_);
    }
    if (accountId_ != 0L) {
      output.writeInt64(5, accountId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (organizationId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, organizationId_);
    }
    if (requestTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, requestTime_);
    }
    if (invokeType_ != com.earth.base.common.BaseRequest.InvokerTypeEnum.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, invokeType_);
    }
    if (brokerUserId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, brokerUserId_);
    }
    if (accountId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, accountId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.earth.base.common.BaseRequest)) {
      return super.equals(obj);
    }
    com.earth.base.common.BaseRequest other = (com.earth.base.common.BaseRequest) obj;

    if (getOrganizationId()
        != other.getOrganizationId()) return false;
    if (getRequestTime()
        != other.getRequestTime()) return false;
    if (invokeType_ != other.invokeType_) return false;
    if (getBrokerUserId()
        != other.getBrokerUserId()) return false;
    if (getAccountId()
        != other.getAccountId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ORGANIZATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOrganizationId());
    hash = (37 * hash) + REQUEST_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRequestTime());
    hash = (37 * hash) + INVOKE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + invokeType_;
    hash = (37 * hash) + BROKER_USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBrokerUserId());
    hash = (37 * hash) + ACCOUNT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAccountId());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.earth.base.common.BaseRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.earth.base.common.BaseRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.earth.base.common.BaseRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.earth.base.common.BaseRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.earth.base.common.BaseRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.earth.base.common.BaseRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.earth.base.common.BaseRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.earth.base.common.BaseRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.earth.base.common.BaseRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.earth.base.common.BaseRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.earth.base.common.BaseRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.earth.base.common.BaseRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.earth.base.common.BaseRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.earth.base.common.BaseRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.earth.base.common.BaseRequest)
      com.earth.base.common.BaseRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.earth.base.common.OrderCommonProto.internal_static_com_earth_base_common_BaseRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.earth.base.common.OrderCommonProto.internal_static_com_earth_base_common_BaseRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.earth.base.common.BaseRequest.class, com.earth.base.common.BaseRequest.Builder.class);
    }

    // Construct using com.earth.base.common.BaseRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      organizationId_ = 0L;
      requestTime_ = 0L;
      invokeType_ = 0;
      brokerUserId_ = 0L;
      accountId_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.earth.base.common.OrderCommonProto.internal_static_com_earth_base_common_BaseRequest_descriptor;
    }

    @java.lang.Override
    public com.earth.base.common.BaseRequest getDefaultInstanceForType() {
      return com.earth.base.common.BaseRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.earth.base.common.BaseRequest build() {
      com.earth.base.common.BaseRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.earth.base.common.BaseRequest buildPartial() {
      com.earth.base.common.BaseRequest result = new com.earth.base.common.BaseRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.earth.base.common.BaseRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.organizationId_ = organizationId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.requestTime_ = requestTime_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.invokeType_ = invokeType_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.brokerUserId_ = brokerUserId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.accountId_ = accountId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.earth.base.common.BaseRequest) {
        return mergeFrom((com.earth.base.common.BaseRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.earth.base.common.BaseRequest other) {
      if (other == com.earth.base.common.BaseRequest.getDefaultInstance()) return this;
      if (other.getOrganizationId() != 0L) {
        setOrganizationId(other.getOrganizationId());
      }
      if (other.getRequestTime() != 0L) {
        setRequestTime(other.getRequestTime());
      }
      if (other.invokeType_ != 0) {
        setInvokeTypeValue(other.getInvokeTypeValue());
      }
      if (other.getBrokerUserId() != 0L) {
        setBrokerUserId(other.getBrokerUserId());
      }
      if (other.getAccountId() != 0L) {
        setAccountId(other.getAccountId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              organizationId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              requestTime_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              invokeType_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              brokerUserId_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              accountId_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long organizationId_ ;
    /**
     * <pre>
     * alias broker_id or org_id
     * </pre>
     *
     * <code>int64 organization_id = 1;</code>
     * @return The organizationId.
     */
    @java.lang.Override
    public long getOrganizationId() {
      return organizationId_;
    }
    /**
     * <pre>
     * alias broker_id or org_id
     * </pre>
     *
     * <code>int64 organization_id = 1;</code>
     * @param value The organizationId to set.
     * @return This builder for chaining.
     */
    public Builder setOrganizationId(long value) {

      organizationId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * alias broker_id or org_id
     * </pre>
     *
     * <code>int64 organization_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrganizationId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      organizationId_ = 0L;
      onChanged();
      return this;
    }

    private long requestTime_ ;
    /**
     * <code>int64 request_time = 2;</code>
     * @return The requestTime.
     */
    @java.lang.Override
    public long getRequestTime() {
      return requestTime_;
    }
    /**
     * <code>int64 request_time = 2;</code>
     * @param value The requestTime to set.
     * @return This builder for chaining.
     */
    public Builder setRequestTime(long value) {

      requestTime_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 request_time = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestTime() {
      bitField0_ = (bitField0_ & ~0x00000002);
      requestTime_ = 0L;
      onChanged();
      return this;
    }

    private int invokeType_ = 0;
    /**
     * <pre>
     *用户，券商，券商代表用户
     * </pre>
     *
     * <code>.com.earth.base.common.BaseRequest.InvokerTypeEnum invoke_type = 3;</code>
     * @return The enum numeric value on the wire for invokeType.
     */
    @java.lang.Override public int getInvokeTypeValue() {
      return invokeType_;
    }
    /**
     * <pre>
     *用户，券商，券商代表用户
     * </pre>
     *
     * <code>.com.earth.base.common.BaseRequest.InvokerTypeEnum invoke_type = 3;</code>
     * @param value The enum numeric value on the wire for invokeType to set.
     * @return This builder for chaining.
     */
    public Builder setInvokeTypeValue(int value) {
      invokeType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户，券商，券商代表用户
     * </pre>
     *
     * <code>.com.earth.base.common.BaseRequest.InvokerTypeEnum invoke_type = 3;</code>
     * @return The invokeType.
     */
    @java.lang.Override
    public com.earth.base.common.BaseRequest.InvokerTypeEnum getInvokeType() {
      com.earth.base.common.BaseRequest.InvokerTypeEnum result = com.earth.base.common.BaseRequest.InvokerTypeEnum.forNumber(invokeType_);
      return result == null ? com.earth.base.common.BaseRequest.InvokerTypeEnum.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *用户，券商，券商代表用户
     * </pre>
     *
     * <code>.com.earth.base.common.BaseRequest.InvokerTypeEnum invoke_type = 3;</code>
     * @param value The invokeType to set.
     * @return This builder for chaining.
     */
    public Builder setInvokeType(com.earth.base.common.BaseRequest.InvokerTypeEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      invokeType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户，券商，券商代表用户
     * </pre>
     *
     * <code>.com.earth.base.common.BaseRequest.InvokerTypeEnum invoke_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearInvokeType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      invokeType_ = 0;
      onChanged();
      return this;
    }

    private long brokerUserId_ ;
    /**
     * <code>int64 broker_user_id = 4;</code>
     * @return The brokerUserId.
     */
    @java.lang.Override
    public long getBrokerUserId() {
      return brokerUserId_;
    }
    /**
     * <code>int64 broker_user_id = 4;</code>
     * @param value The brokerUserId to set.
     * @return This builder for chaining.
     */
    public Builder setBrokerUserId(long value) {

      brokerUserId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 broker_user_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBrokerUserId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      brokerUserId_ = 0L;
      onChanged();
      return this;
    }

    private long accountId_ ;
    /**
     * <code>int64 account_id = 5;</code>
     * @return The accountId.
     */
    @java.lang.Override
    public long getAccountId() {
      return accountId_;
    }
    /**
     * <code>int64 account_id = 5;</code>
     * @param value The accountId to set.
     * @return This builder for chaining.
     */
    public Builder setAccountId(long value) {

      accountId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 account_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccountId() {
      bitField0_ = (bitField0_ & ~0x00000010);
      accountId_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.earth.base.common.BaseRequest)
  }

  // @@protoc_insertion_point(class_scope:com.earth.base.common.BaseRequest)
  private static final com.earth.base.common.BaseRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.earth.base.common.BaseRequest();
  }

  public static com.earth.base.common.BaseRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BaseRequest>
      PARSER = new com.google.protobuf.AbstractParser<BaseRequest>() {
    @java.lang.Override
    public BaseRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BaseRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BaseRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.earth.base.common.BaseRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

