// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/earth/base/common/order_common.proto

// Protobuf Java Version: 3.25.3
package com.earth.base.common;

public interface DecimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.earth.base.common.Decimal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 原始字符串，比如 "123.45"
   * </pre>
   *
   * <code>string str = 1;</code>
   * @return The str.
   */
  java.lang.String getStr();
  /**
   * <pre>
   * 原始字符串，比如 "123.45"
   * </pre>
   *
   * <code>string str = 1;</code>
   * @return The bytes for str.
   */
  com.google.protobuf.ByteString
      getStrBytes();

  /**
   * <pre>
   * 去掉小数点的整数，比如 12345
   * </pre>
   *
   * <code>int64 unscaled_value = 2;</code>
   * @return The unscaledValue.
   */
  long getUnscaledValue();

  /**
   * <pre>
   * 小数位数，比如 2
   * </pre>
   *
   * <code>int32 scale = 3;</code>
   * @return The scale.
   */
  int getScale();
}
