// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/earth/base/common/order_common.proto

// Protobuf Java Version: 3.25.3
package com.earth.base.common;

/**
 * <pre>
 *
 * 订单子类型
 *
 * GTC （取消前有效） - 取消前有效定单将在系统内和市场上一直工作到被执行或被取消。 GTC定单将在以下情况发生时被自动取消：
 *     如果某个证券的公司活动引起股票分股（正向或反向），股票交换、或股票分配。
 *     如果你在90 天内没有登录你的IB%COMPANY_ACRONYM% 账户。
 *     在当前季度后的下一个日历季度末。例如，一个在2011年第三季度内下的定单将在2012年第一季度末被取消。如果最后一天为非交易日，取消将发生在该季度内最后交易日结束时。例如，如果季度的最后一天是周日，则定单将在之前的周五被取消。
 *     修改过的定单将被指定一个新的“自动过期”日期与在当前季度后的日历季度末的原则保持一致。
 *
 * FOK （全数执行或立即取消） - 如果整个全数执行或立即取消定单没有在其成为可交易时被立即执行，则整个定单被取消。
 *
 * IOC （立刻执行或取消） - 任何立即执行或取消 定单的未执行部分只要一旦在市场上成为可交易的即被立即取消。
 *
 * GTM  (撮合成功则取消) - 如果与其他账户撮合成功则取消订单
 * </pre>
 *
 * Protobuf enum {@code com.earth.base.common.OrderTimeInForceEnum}
 */
public enum OrderTimeInForceEnum
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 取消前有效
   * </pre>
   *
   * <code>GTC = 0;</code>
   */
  GTC(0),
  /**
   * <pre>
   * 全数执行或立即取消
   * </pre>
   *
   * <code>FOK = 1;</code>
   */
  FOK(1),
  /**
   * <pre>
   * 立刻执行或取消
   * </pre>
   *
   * <code>IOC = 2;</code>
   */
  IOC(2),
  /**
   * <pre>
   * 指定日期前有效
   * </pre>
   *
   * <code>GTD = 3;</code>
   */
  GTD(3),
  /**
   * <pre>
   * 日内订单
   * </pre>
   *
   * <code>Today = 4;</code>
   */
  Today(4),
  /**
   * <pre>
   * 撮合成功则取消
   * </pre>
   *
   * <code>GTM = 100;</code>
   */
  GTM(100),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 取消前有效
   * </pre>
   *
   * <code>GTC = 0;</code>
   */
  public static final int GTC_VALUE = 0;
  /**
   * <pre>
   * 全数执行或立即取消
   * </pre>
   *
   * <code>FOK = 1;</code>
   */
  public static final int FOK_VALUE = 1;
  /**
   * <pre>
   * 立刻执行或取消
   * </pre>
   *
   * <code>IOC = 2;</code>
   */
  public static final int IOC_VALUE = 2;
  /**
   * <pre>
   * 指定日期前有效
   * </pre>
   *
   * <code>GTD = 3;</code>
   */
  public static final int GTD_VALUE = 3;
  /**
   * <pre>
   * 日内订单
   * </pre>
   *
   * <code>Today = 4;</code>
   */
  public static final int Today_VALUE = 4;
  /**
   * <pre>
   * 撮合成功则取消
   * </pre>
   *
   * <code>GTM = 100;</code>
   */
  public static final int GTM_VALUE = 100;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static OrderTimeInForceEnum valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static OrderTimeInForceEnum forNumber(int value) {
    switch (value) {
      case 0: return GTC;
      case 1: return FOK;
      case 2: return IOC;
      case 3: return GTD;
      case 4: return Today;
      case 100: return GTM;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OrderTimeInForceEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OrderTimeInForceEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OrderTimeInForceEnum>() {
          public OrderTimeInForceEnum findValueByNumber(int number) {
            return OrderTimeInForceEnum.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.earth.base.common.OrderCommonProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final OrderTimeInForceEnum[] VALUES = values();

  public static OrderTimeInForceEnum valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private OrderTimeInForceEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.earth.base.common.OrderTimeInForceEnum)
}

