// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/earth/base/common/order_common.proto

// Protobuf Java Version: 3.25.3
package com.earth.base.common;

public final class OrderCommonProto {
  private OrderCommonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_earth_base_common_BaseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_earth_base_common_BaseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_earth_base_common_Decimal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_earth_base_common_Decimal_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(com/earth/base/common/order_common.pro" +
      "to\022\025com.earth.base.common\"\200\002\n\013BaseReques" +
      "t\022\027\n\017organization_id\030\001 \001(\003\022\024\n\014request_ti" +
      "me\030\002 \001(\003\022G\n\013invoke_type\030\003 \001(\01622.com.eart" +
      "h.base.common.BaseRequest.InvokerTypeEnu" +
      "m\022\026\n\016broker_user_id\030\004 \001(\003\022\022\n\naccount_id\030" +
      "\005 \001(\003\"M\n\017InvokerTypeEnum\022\013\n\007UNKNOWN\020\000\022\010\n" +
      "\004USER\020\001\022\020\n\014ORGANIZATION\020\002\022\021\n\rAGENT_OF_US" +
      "ER\020\003\"=\n\007Decimal\022\013\n\003str\030\001 \001(\t\022\026\n\016unscaled" +
      "_value\030\002 \001(\003\022\r\n\005scale\030\003 \001(\005*\255\001\n\rOrderTyp" +
      "eEnum\022\t\n\005LIMIT\020\000\022\022\n\016MARKET_OF_BASE\020\002\022\023\n\017" +
      "MARKET_OF_QUOTE\020\003\022\017\n\013LIMIT_MAKER\020\004\022\007\n\003CO" +
      "M\020\005\022\016\n\nSTOP_LIMIT\020\006\022\016\n\nLOCAL_ONLY\020\007\022\016\n\nL" +
      "IMIT_FREE\020\010\022\024\n\020LIMIT_MAKER_FREE\020\t\022\010\n\004STO" +
      "P\020\n*N\n\024OrderTimeInForceEnum\022\007\n\003GTC\020\000\022\007\n\003" +
      "FOK\020\001\022\007\n\003IOC\020\002\022\007\n\003GTD\020\003\022\t\n\005Today\020\004\022\007\n\003GT" +
      "M\020d*4\n\rOrderSideEnum\022\007\n\003BUY\020\000\022\010\n\004SELL\020\001\022" +
      "\020\n\014UNKNOWN_SIDE\020\002BB\n\025com.earth.base.comm" +
      "onB\020OrderCommonProtoP\001Z\025com_earth_base_c" +
      "ommonb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_earth_base_common_BaseRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_earth_base_common_BaseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_earth_base_common_BaseRequest_descriptor,
        new java.lang.String[] { "OrganizationId", "RequestTime", "InvokeType", "BrokerUserId", "AccountId", });
    internal_static_com_earth_base_common_Decimal_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_earth_base_common_Decimal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_earth_base_common_Decimal_descriptor,
        new java.lang.String[] { "Str", "UnscaledValue", "Scale", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
