// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/earth/base/common/order_common.proto

// Protobuf Java Version: 3.25.3
package com.earth.base.common;

/**
 * Protobuf enum {@code com.earth.base.common.OrderSideEnum}
 */
public enum OrderSideEnum
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>BUY = 0;</code>
   */
  BUY(0),
  /**
   * <code>SELL = 1;</code>
   */
  SELL(1),
  /**
   * <code>UNKNOWN_SIDE = 2;</code>
   */
  UNKNOWN_SIDE(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>BUY = 0;</code>
   */
  public static final int BUY_VALUE = 0;
  /**
   * <code>SELL = 1;</code>
   */
  public static final int SELL_VALUE = 1;
  /**
   * <code>UNKNOWN_SIDE = 2;</code>
   */
  public static final int UNKNOWN_SIDE_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static OrderSideEnum valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static OrderSideEnum forNumber(int value) {
    switch (value) {
      case 0: return BUY;
      case 1: return SELL;
      case 2: return UNKNOWN_SIDE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OrderSideEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OrderSideEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OrderSideEnum>() {
          public OrderSideEnum findValueByNumber(int number) {
            return OrderSideEnum.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.earth.base.common.OrderCommonProto.getDescriptor().getEnumTypes().get(2);
  }

  private static final OrderSideEnum[] VALUES = values();

  public static OrderSideEnum valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private OrderSideEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.earth.base.common.OrderSideEnum)
}

